application: hello-flask-app-engine
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /oauth/.*
  script: api.oauth_api.app
- url: /api/user/.*
  script: api.user_api.app
- url: /api/client/.*
  script: api.client_api.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

skip_files:
- integration_tests/.*
- unit_tests/.*
- run_unit_tests.py